spring:
  application:
    name: ticket
  datasource:
    url: jdbc:postgresql://localhost:5432/fenixdb
    username: fenix
    password: fenix123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
server:
  port: 8080