spring:
  application:
    name: ticket
  datasource:
    url: jdbc:postgresql://localhost:5432/fenixdb
    username: postgres
    password: root-1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    locations: classpath:db/migration
server:
  port: 8080